sudo: required
language: c++

# value for --git-upstream-tag should be replaced by the result of the following...
# git show-branch --sha1-name debian develop | tail -1 | grep -o '[[:alnum:]]*' | head -1

env:
  global:
    - TRAVIS_DEBIAN_GIT_BUILDPACKAGE="gbp buildpackage --git-upstream-tag=f55209d"
    - TRAVIS_DEBIAN_DISTRIBUTION="sid"
    - TRAVIS_DEBIAN_EXTRA_REPOSITORY_GPG_URL=""
    - TRAVIS_DEBIAN_EXTRA_REPOSITORY=""

services:
  - docker

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

branches:
  except:
    - /^debian\/\d/
