.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Katsuki Kobayashi <rare@tirasweel.org>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "Tomighty" "1"  "Feb. 9, 2017" "tomighty"

.SH "NAME"
tomighty \- Desktop Timer App for Pomodoro Technique
.SH OVERVIEW
.br
A desktop timer app for the Pomodoro Technique® written in C++ on top of Qt 5.
It's designed to be:
.PP
.PD 0
.TP
.PD
.PD
\(bu
Simple
.TP
\(bu
Non-distracting
.TP
\(bu
Unintrusive
.TP
\(bu
Reasonably configurable
.TP
\(bu
Extensible (with plugins)
.TP
\(bu
Cross-platformq
.PP
When the application starts, a little tomato icon is shown on the system tray.
Its color indicates the current state of the timer. By clicking on the tray icon the main application menu pops up.
.SH "AUTHOR(S)"
.TP
.B Célio Cidral Junior

