.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Katsuki Kobayashi <rare@tirasweel.org>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH Tomighty 1 "October  1 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
tomighty \- desktop timer app for the Pomodoro Technique\*R
.SH DESCRIPTION
.Pp
\fBtomighty\fP is a desktop timer app for the Pomodoro Technique® written in C++ on top of Qt 5.

It's designed to be:
.IP *
Simple
.IP *
Non-distracting
.IP *
Unintrusive
.IP *
Reasonably configurable
.IP *
Extensible (with plugins)
.IP *
Cross-platform

.SH AUTHOR

\fBtomighty\fP
was written by Célio Cidral Junior <ccidral@gmail.com>.
This manual page was written by Katsuki Kobayashi <rare@tirasweel.org>
for the Debian GNU/Linux system
but may be used by others under the same license as
\fBtomighty\fP
itself.
